# This is a basic workflow to help you get started with Actions

name: undefined-os

# Controls when the workflow will run
on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm i

      # Runs a set of commands using the runners shell
      - name: Check code with ESLint
        run: npm run eslint
